# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy: 
 matrix:
   linux:
    operatingSystem: 'ubuntu-latest'
   windows: 
    operatingSystem: 'windows-latest'


pool:
  vmImage: $(operatingSystem)

steps:
- script: echo Running on the $(operatingSystem)
  displayName: 'Run a one-line script'

